"""empty message

Revision ID: 23b9b8cdbcd1
Revises: 3adf765ab643
Create Date: 2022-06-08 10:01:15.130158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b9b8cdbcd1'
down_revision = '3adf765ab643'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmation_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmation_token')
    # ### end Alembic commands ###

